### ISSUE TITLE
How to cheat game.

### ISSUE THREAD

**Issue by NhanBlack** [ramenjuniti/VR_Avoid_Game#1]
Hello ramenjuniti. I have just played your game and love it. it has a small error when i point cursor into wall left or right. It's cheats no die.

**Comment by ramenjuniti** [comment]
Hello NhanBlack. Thank you for playing this game. Analyzing the issue you pointed out,
It seems that the range of hit judgment in this game was narrow, so I made it a little wider.

**Comment by NhanBlack** [comment]
my mean is turn left or right 90 degree near wall(not box) you will undead.

**Comment by ramenjuniti** [comment]
I am sorry to have kept you waiting long. I added a death by course-out to this game.
